{{- $configMap := (lookup "v1" "ConfigMap" .Release.Namespace "bp-webservice-gateway-trembita-business-processes") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: bp-webservice-gateway-trembita-business-processes
{{- if $configMap }}
data:
  {{ $configMap.data | toYaml | nindent 2 }}
{{- else }}
data:
  trembita-business-processes.yml: |-
{{- end }}
