{{- $configMap := (lookup "v1" "ConfigMap" .Values.namespace "business-process-modeler-element-templates") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: business-process-modeler-element-templates
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  {{- if $configMap }}
data:
  {{ $configMap.data | toYaml | nindent 2 }}
  {{- else }}
data:
  business-process-modeler-element-templates.json: |
    [
    ]
    };
{{- end }}
