apiVersion: v1
kind: ConfigMap
metadata:
  name: history-excerptor
data:
  history-excerptor: |
    apiVersion: v2.edp.epam.com/v1alpha1
    kind: Codebase
    metadata:
      name: history-excerptor
      labels:
        recreateByCleanup: "true"
    spec:
      emptyProject: false
      commitMessagePattern: null
      jenkinsSlave: dataplatform-jenkins-agent
      gitUrlPath: null
      defaultBranch: master
    {{- if eq .Values.edpProject "control-plane" }}
      branchToCopyInDefaultBranch: {{ .Values.codebases.registryRegulations.historyExcerptorRepoVersion }}
    {{- else }}
      branchToCopyInDefaultBranch: {{ .Values.registryRegulations.historyExcerptorRepoVersion }}
    {{- end }}
      buildTool: none
      route: null
      perf: null
      versioning:
        startFrom: 0.0.1
        type: edp
      jobProvisioning: registry
      repository:
    {{- if eq .Values.edpProject "control-plane" }}
        url: {{ .Values.codebases.registryRegulations.historyExcerptorUrl }}
    {{- else }}
        url: 'https://gerrit-{{ .Values.edpProject }}.{{ .Values.dnsWildcard }}/mdtu-ddm/data-architecture/devops-application/history-excerptor-chart'
    {{- end }}
      lang: groovy-pipeline
      deploymentScript: ''
      strategy: clone
      jiraIssueMetadataPayload: null
      gitServer: gerrit
      testReportFramework: null
      ticketNamePattern: null
      type: library
      database: null
      description: null
      framework: null
      ciTool: Jenkins
    ---
    apiVersion: v2.edp.epam.com/v1alpha1
    kind: CodebaseBranch
    metadata:
    {{- if eq .Values.edpProject "control-plane" }}
      name: history-excerptor-master
    {{- else }}
      name: history-excerptor-{{ .Values.registryRegulations.historyExcerptorRepoVersion | toString | replace "." "-" | replace "/" "-" | lower }}
    {{- end }}
      labels:
        affiliatedWith: "history-excerptor"
        recreateByCleanup: "true"
    spec:
      branchName: master
      codebaseName: history-excerptor
      fromCommit: ''
      release: false
      version: 0.0.1
