{{- $configMap := (lookup "v1" "ConfigMap" .Release.Namespace "registry-environment-js") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-environment-js
{{- if $configMap }}
data:
  {{ $configMap.data | toYaml | nindent 2 }}
{{- else }}
data:
  registry-environment.js: |
    const REGISTRY_ENVIRONMENT_VARIABLES = {
    };
{{- end }}
