apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: admin-tools-kong-proxy
  annotations:
    {{ template "admin-routes.whitelist.annotation" . }}
spec:
  host: {{ template "admin-tools.hostname" . }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: istio-ingressgateway-{{ .Values.stageName }}
  port:
    targetPort: http2
