kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  name: {{ .Values.externalSecrets.externalSystemsExternalSecrets.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.externalSystemsExternalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.externalSystemsExternalSecrets.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.externalSystemsExternalSecrets.target.name }}
  dataFrom:
    - extract:
        key: "registry-kv/registry/{{ .Values.namespace }}/external-systems"
