apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: external-system-api-kong-proxy
spec:
  host: {{ template "external-system-api.hostname" . }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: istio-ingressgateway-{{ .Values.stageName }}
  port:
    targetPort: http2