{{- $root := .Values }}
{{- $release := .Release }}
{{- $region := $root.global.region }}
{{- range $realm := .Values.keycloak.realms }}
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    created-by: {{ $root.appLabel }}
  name: {{ $realm.name }}
spec:
  keycloakOwner: {{ $realm.keycloakOwner }}
  realmName:  {{ template "keycloak.realmName" (dict "root" $ "realm" $realm "release" $release) }}
  {{- if or (eq $realm.name "citizen-portal")  (eq $realm.name "officer-portal") }}
  frontendUrl: {{ template "keycloak.frontendUrl" $ }}
  {{- end }}
  ssoRealmEnabled: {{ and $realm.ssoRealm.enabled (or (ne $region "global") (eq $realm.name "admin")) }}
  {{- if and $realm.ssoRealm.enabled (or (ne $region "global") (eq $realm.name "admin")) }}
  ssoAutoRedirectEnabled: {{ $realm.ssoRealm.autoRedirectEnabled }}
  ssoRealmName: {{ tpl $realm.ssoRealm.name $ }}
  realmEventConfig: {{ $root.keycloak.realmEventConfig | toYaml | nindent 4 }}
  {{- end }}
  {{- if $realm.users }}
  users: {{ $realm.users | toYaml | nindent 4 }}
  {{- end }}
  {{- if eq $region "global" }}
  themes:
    loginTheme: keycloak
  {{- else if $realm.loginTheme }}
  themes:
    loginTheme: {{ $realm.loginTheme }}
  {{- end }}
  {{- if $realm.loginTheme }}
  browserSecurityHeaders:
    {{- if eq $realm.name "citizen-portal" }}
    contentSecurityPolicy: "frame-src 'self' https://{{ (urlParse $root.keycloak.citizenAuthFlow.widget.url).host }}; frame-ancestors 'self'; object-src 'none';"
    {{- else }}
    contentSecurityPolicy: "frame-src 'self' https://{{ (urlParse $root.signWidget.url).host }}; frame-ancestors 'self'; object-src 'none';"
    {{- end }}
  {{- end }}
  {{- if eq $region "global" }}
  browserFlow: browser
  {{- else if eq $realm.name "officer-portal" }}
  browserFlow: {{ $root.keycloak.realms.officerPortal.browserFlow }}
  {{- else }}
  {{- if $realm.browserFlow }}
  browserFlow: {{ $realm.browserFlow }}
  {{- end }}
  {{- end }}
  {{- end }}

