apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.trembitaRegistriesSecrets.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.trembitaRegistriesSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.trembitaRegistriesSecrets.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.trembitaRegistriesSecrets.target.name }}
  dataFrom:
    - extract:
        key: "registry-kv/registry/{{ .Values.namespace }}/trembita-registries"
